// Generate upload metadata
const fs = require('fs');
const path = require('path');

const uploadedDir = 'youtube-inbox/uploaded';
const videos = fs.readdirSync(uploadedDir)
    .filter(f => ['.mp4', '.webm', '.mov', '.avi'].includes(path.extname(f).toLowerCase()));

function parseVideoInfo(basename) {
    const match = basename.match(/sainted-word-(\d{4})-(\d{2})-(\d{2})T(\d{2})-(\d{2})(?:-(\d{2}))?/);
    let date = null;
    if (match) {
        date = new Date(`${match[1]}-${match[2]}-${match[3]}T${match[4]}:${match[5]}:${match[6] || '00'}`);
    }
    
    let mood = 'Ambient';
    const lower = basename.toLowerCase();
    if (lower.includes('ambient') || lower.includes('drone')) mood = 'Ambient';
    else if (lower.includes('beat') || lower.includes('rhythm')) mood = 'Rhythmic';
    else if (lower.includes('dark') || lower.includes('noir')) mood = 'Dark';
    else if (lower.includes('bright') || lower.includes('light')) mood = 'Bright';
    else if (lower.includes('dream') || lower.includes('sleep')) mood = 'Dreamy';
    else if (lower.includes('energy') || lower.includes('pulse')) mood = 'Energetic';
    else if (lower.includes('vysio')) mood = 'Vysio';
    else if (lower.includes('eclipse')) mood = 'Eclipse';
    else if (lower.includes('cyberpunk')) mood = 'Cyberpunk';
    
    return { 
        basename, 
        date, 
        mood,
        title: date ? `Sainted Word - ${date.toISOString().split('T')[0]} - ${mood}` : `Sainted Word - ${mood}`,
        description: `Generated by #SaintedWordRecords AI art pipeline.

#SaintedWordRecords #AIArt #GenerativeMusic #${mood}`,
        tags: ['SaintedWordRecords', 'AIArt', 'GenerativeMusic', mood]
    };
}

const metadata = videos.map(v => {
    const info = parseVideoInfo(path.basename(v, path.extname(v)));
    const thumbFile = `${info.basename}_thumb.jpg`;
    return {
        video: v,
        thumbnail: fs.existsSync(path.join(uploadedDir, thumbFile)) ? thumbFile : null,
        ...info
    };
});

// Write JSON
fs.writeFileSync('youtube-inbox/upload-metadata.json', JSON.stringify(metadata, null, 2));

// Write markdown table
let md = '# YouTube Upload Metadata\n\n';
md += '## All Videos (' + metadata.length + ')\n\n';
md += '| # | Video | Title | Tags | Thumbnail |\n';
md += '|---|-------|-------|------|----------|\n';

metadata.forEach((m, i) => {
    const tags = m.tags.join(', ');
    md += `| ${i+1} | ${m.basename} | ${m.title} | ${tags} | ${m.thumbnail ? '✓' : '✗'} |\n`;
});

md += '\n## Details\n\n';
metadata.forEach((m, i) => {
    md += `### ${i+1}. ${m.title}\n`;
    md += `- **File**: ${m.video}\n`;
    md += `- **Thumbnail**: ${m.thumbnail || 'N/A'}\n`;
    md += `- **Tags**: ${m.tags.join(', ')}\n`;
    md += `- **Description**:\n`;
    md += '```\n' + m.description + '\n```\n\n';
});

fs.writeFileSync('youtube-inbox/upload-list.md', md);

console.log(`Generated metadata for ${metadata.length} videos`);
console.log('Files:');
console.log('  - youtube-inbox/upload-metadata.json');
console.log('  - youtube-inbox/upload-list.md');
