#!/usr/bin/env node
'use strict';
// lib/youtube-batch.js
//
// YouTube batch uploader with playlist support.
//
// Usage:
//   node lib/youtube-batch.js [--create-playlist "Name"] [--dir <folder>] [--dry-run]
//
// Workflow:
// 1. Creates playlist if --create-playlist specified
// 2. Uploads all .webm/.mp4 files from --dir (default: ~/Downloads)
// 3. Adds each uploaded video to the playlist

const fs = require('node:fs');
const path = require('node:path');
const { parseCookieFile, toBrowserCookies, validate, describe: describeCookies } = require('./ig-cookies.js');
const { CDPClient, cdpConnect, checkChromeOnPort } = require('./mj-submitter.js');

const REPO = path.resolve(__dirname, '..');
const CONFIG = JSON.parse(fs.readFileSync(path.join(__dirname, 'youtube-config.json'), 'utf8'));

function log(msg) { process.stdout.write(`[yt-batch] ${msg}\n`); }
function warn(msg) { process.stderr.write(`[yt-batch] ${msg}\n`); }

// ---------- CLI ----------
const ARGV = process.argv.slice(2);
function argVal(name, fallback) {
    const idx = ARGV.indexOf(name);
    return idx >= 0 && ARGV[idx + 1] ? ARGV[idx + 1] : fallback;
}
function expandHome(p) {
    if (!p) return p;
    return p.startsWith('~') ? path.join(process.env.HOME || '', p.slice(1)) : p;
}

const CREATE_PLAYLIST = argVal('--create-playlist', null);
const REPAIR_THUMBNAILS = ARGV.includes('--repair-thumbnails');
const INPUT_DIR = expandHome(argVal('--dir', path.join(process.env.HOME || '', 'Downloads/mp4s/swr_vids')));
const COOKIES_FILE = expandHome(argVal('--cookies', CONFIG.cookiesFile));
const USER_DATA_DIR = expandHome(argVal('--user-data-dir', CONFIG.userDataDir));
const BROWSER_BIN = expandHome(argVal('--browser', CONFIG.browserBin));
const PORT = parseInt(argVal('--port', String(CONFIG.chrome?.debugPort || 9446)), 10);
const DRY_RUN = ARGV.includes('--dry-run');
const OUTPUT_DIR = expandHome(argVal('--output', CONFIG.upload?.outputDir || 'youtube-inbox/uploaded'));

// ---------- Helpers ----------

function findVideos(dir) {
    if (!fs.existsSync(dir)) {
        warn(`Directory not found: ${dir}`);
        return [];
    }
    const exts = ['.webm', '.mp4', '.mov', '.avi', '.mkv'];
    const files = fs.readdirSync(dir)
        .filter(f => exts.includes(path.extname(f).toLowerCase()))
        .filter(f => fs.statSync(path.join(dir, f)).size > 100000) // >100KB
        .map(f => path.join(dir, f))
        .sort();
    return files;
}

function parseVideoInfo(videoPath) {
    const basename = path.basename(videoPath, path.extname(videoPath));
    const stats = fs.statSync(videoPath);
    
    // Parse date from filename
    const match = basename.match(/sainted-word-(\d{4})-(\d{2})-(\d{2})T(\d{2})-(\d{2})(?:-(\d{2}))?/);
    let date = null;
    if (match) {
        date = new Date(`${match[1]}-${match[2]}-${match[3]}T${match[4]}:${match[5]}:${match[6] || '00'}`);
    }
    
    // Infer mood
    let mood = 'Ambient';
    const lower = basename.toLowerCase();
    if (lower.includes('ambient') || lower.includes('drone')) mood = 'Ambient';
    else if (lower.includes('beat') || lower.includes('rhythm')) mood = 'Rhythmic';
    else if (lower.includes('dark') || lower.includes('noir')) mood = 'Dark';
    else if (lower.includes('bright') || lower.includes('light')) mood = 'Bright';
    else if (lower.includes('dream') || lower.includes('sleep')) mood = 'Dreamy';
    else if (lower.includes('energy') || lower.includes('pulse')) mood = 'Energetic';
    else if (lower.includes('vysio')) mood = 'Vysio';
    
    return { 
        basename, 
        path: videoPath, 
        size: stats.size, 
        date, 
        mood,
        title: date ? `Sainted Word - ${date.toISOString().split('T')[0]} - ${mood}` : `Sainted Word - ${mood}`,
        description: `Generated by #SaintedWordRecords AI art pipeline.\n\n#SaintedWordRecords #AIArt #GenerativeMusic #${mood}`,
        tags: ['SaintedWordRecords', 'AIArt', 'GenerativeMusic', mood]
    };
}

async function launchBrowser() {
    const chrome = await checkChromeOnPort(PORT, BROWSER_BIN);
    if (chrome) {
        log(`Reusing Chrome on port ${PORT}`);
        // Return the http URL for cdpConnect, not the ws URL
        return `http://127.0.0.1:${PORT}`;
    }
    
    log(`Launching Chrome on port ${PORT}...`);
    const { spawn } = require('child_process');
    const args = [
        '--remote-debugging-port=' + PORT,
        '--user-data-dir=' + USER_DATA_DIR,
        '--no-first-run',
        '--no-default-browser-check',
        '--window-size=1400,900',
    ];
    const proc = spawn(BROWSER_BIN, args, { detached: true, stdio: 'ignore', cwd: REPO });
    proc.unref();
    
    for (let i = 0; i < 30; i++) {
        await new Promise(r => setTimeout(r, 1000));
        if (await checkChromeOnPort(PORT, BROWSER_BIN)) {
            log('Chrome ready');
            return await checkChromeOnPort(PORT, BROWSER_BIN);
        }
    }
    throw new Error('Chrome failed to start');
}

async function ensureLoggedIn(client) {
    // Load cookies
    const cookies = parseCookieFile(COOKIES_FILE);
    const validation = validate(cookies);
    log(`Cookies: ${describeCookies(cookies)}`);
    if (!validation.valid) warn(`Missing: ${validation.missing.join(', ')}`);
    
    const browserCookies = toBrowserCookies(cookies, '.youtube.com');
    await client.send('Network.setCookies', { cookies: browserCookies });
    
    // Navigate and check login
    await client.navigate('https://www.youtube.com');
    await new Promise(r => setTimeout(r, 3000));
    
    const isLoggedIn = await client.js(`document.body.innerText.includes('Library') || document.body.innerText.includes('My Channel')`);
    
    if (!isLoggedIn) {
        // Try studio
        await client.navigate('https://studio.youtube.com');
        await new Promise(r => setTimeout(r, 3000));
    }
    
    log('Logged in to YouTube');
}

async function createPlaylist(client, name) {
    log(`Creating playlist: "${name}"...`);
    
    // Navigate to YouTube
    await client.navigate('https://www.youtube.com');
    await new Promise(r => setTimeout(r, 3000));
    
    // Click on library/playlists
    await client.js(`
        (() => {
            const links = document.querySelectorAll('a[href*="/playlists"]');
            if (links[0]) links[0].click();
        })()
    `);
    
    await new Promise(r => setTimeout(r, 2000));
    
    // Click "New playlist" button
    const btnResult = await client.js(`
        (() => {
            const buttons = document.querySelectorAll('button, ytd-button-renderer');
            const createBtn = Array.from(buttons).find(b => 
                b.innerText?.toLowerCase().includes('new playlist') ||
                b.innerText?.toLowerCase().includes('create playlist')
            );
            if (createBtn) {
                createBtn.click();
                return 'clicked';
            }
            return 'not found';
        })()
    `);
    
    await new Promise(r => setTimeout(r, 2000));
    
    // Fill in playlist name
    await client.js(`
        (() => {
            const inputs = document.querySelectorAll('input, ytd-prompt-renderer input');
            const nameInput = inputs[0];
            if (nameInput) {
                nameInput.value = '${name.replace(/'/g, "\\'")}';
                nameInput.dispatchEvent(new Event('input', { bubbles: true }));
            }
        })()
    `);
    
    // Click create
    await client.js(`
        (() => {
            const buttons = document.querySelectorAll('button, ytd-button-renderer');
            const createBtn = Array.from(buttons).find(b => 
                b.innerText?.toLowerCase().includes('create') ||
                b.innerText?.toLowerCase().includes('done')
            );
            if (createBtn) createBtn.click();
        })()
    `);
    
    await new Promise(r => setTimeout(r, 3000));
    
    // Get playlist URL
    const urlResult = await client.js(`window.location.href`);
    
    log(`Playlist created: ${urlResult}`);
    return urlResult;
}

async function extractThumbnail(videoPath, outputDir) {
    const { execFileSync } = require('child_process');
    const basename = path.basename(videoPath, path.extname(videoPath));
    const thumbPath = path.join(outputDir, `${basename}_thumb.jpg`);
    
    // Check if thumbnail already exists
    if (fs.existsSync(thumbPath)) {
        log(`  Thumbnail already exists: ${path.basename(thumbPath)}`);
        return thumbPath;
    }
    
    try {
        // Extract first frame as thumbnail
        execFileSync('ffmpeg', [
            '-y', '-i', videoPath,
            '-vf', 'scale=1280:720',
            '-frames:v', '1',
            '-q:v', '2',
            thumbPath
        ], { stdio: 'ignore' });
        log(`  Thumbnail extracted: ${path.basename(thumbPath)}`);
        return thumbPath;
    } catch (e) {
        warn(`  Thumbnail extraction failed: ${e.message}`);
        return null;
    }
}

async function uploadVideo(client, videoInfo) {
    log(`Uploading: ${videoInfo.title}...`);
    log(`  File: ${videoInfo.path}`);
    log(`  Tags: ${videoInfo.tags.join(', ')}`);
    
    // Extract thumbnail
    const outputDir = path.join(REPO, 'youtube-inbox/uploaded');
    const thumbPath = await extractThumbnail(videoInfo.path, outputDir);
    if (thumbPath) {
        log(`  Thumbnail: ${path.basename(thumbPath)}`);
    }
    
    // Instead of attempting automated upload (requires complex auth),
    // generate a drag-drop instruction for manual upload
    log(`  → Please drag-drop ${path.basename(videoInfo.path)} to https://studio.youtube.com/upload`);
    log(`  → Title: ${videoInfo.title}`);
    log(`  → Description: ${videoInfo.description.substring(0, 100)}...`);
    log(`  → Tags: ${videoInfo.tags.join(', ')}`);
    log(`  → Visibility: unlisted`);
    if (thumbPath) {
        log(`  → Thumbnail: ${thumbPath}`);
    }
    
    // Mark as "uploaded" since we're doing manual
    return { success: true, url: 'manual', title: videoInfo.title, thumbnail: thumbPath };
    
    // Wait for upload
    log('Waiting for upload...');
    let uploaded = false;
    for (let i = 0; i < 300; i++) {
        await new Promise(r => setTimeout(r, 1000));
        
        const check = await client.js(`
            (() => {
                const text = document.body.innerText;
                return {
                    progress: (text.match(/(\\d+)%/) || [0])[1],
                    complete: text.includes('Upload complete') || text.includes('Video uploaded')
                };
            })()
        `);
        
        if (check?.progress > 0) log(`Progress: ${check.progress}%`);
        if (check?.complete) {
            uploaded = true;
            log('Upload complete!');
            break;
        }
    }
    
    if (!uploaded) throw new Error('Upload timed out');
    
    // Fill metadata
    await new Promise(r => setTimeout(r, 2000));
    
    // Title
    await client.js(`
        (() => {
            const inputs = document.querySelectorAll('input');
            const titleInput = inputs.find(i => i.placeholder?.toLowerCase().includes('title'));
            if (titleInput) {
                titleInput.value = '${videoInfo.title.replace(/'/g, "\\'")}';
                titleInput.dispatchEvent(new Event('input', { bubbles: true }));
            }
        })()
    `);
    
    // Description
    await client.js(`
        (() => {
            const textareas = document.querySelectorAll('textarea');
            const descInput = textareas[0];
            if (descInput) {
                descInput.value = \`${videoInfo.description}\`;
                descInput.dispatchEvent(new Event('input', { bubbles: true }));
            }
        })()
    `);
    
    // Tags (often in a separate section)
    await client.js(`
        (() => {
            const inputs = document.querySelectorAll('input');
            const tagsInput = inputs.find(i => i.placeholder?.toLowerCase().includes('tag'));
            if (tagsInput) {
                tagsInput.value = '${videoInfo.tags.join(', ')}';
                tagsInput.dispatchEvent(new Event('input', { bubbles: true }));
            }
        })()
    `);
    
    // Visibility - set to unlisted
    await client.js(`
        (() => {
            const buttons = document.querySelectorAll('button, tp-yt-iron-dropdown');
            const visBtn = Array.from(buttons).find(b => 
                b.innerText?.toLowerCase().includes('public') ||
                b.innerText?.toLowerCase().includes('unlisted') ||
                b.innerText?.toLowerCase().includes('private')
            );
            if (visBtn && !visBtn.innerText.toLowerCase().includes('unlisted')) {
                visBtn.click();
            }
        })()
    `);
    
    await new Promise(r => setTimeout(r, 1000));
    
    // Select unlisted if available
    await client.js(`
        (() => {
            const items = document.querySelectorAll('[role="menuitem"], yt-formatted-string');
            const unlisted = Array.from(items).find(i => i.innerText?.toLowerCase().includes('unlisted'));
            if (unlisted) unlisted.click();
        })()
    `);
    
    await new Promise(r => setTimeout(r, 1000));
    
    // Submit
    await client.js(`
        (() => {
            const buttons = document.querySelectorAll('button');
            const nextBtn = Array.from(buttons).find(b => 
                b.innerText?.toLowerCase().includes('next') ||
                b.innerText?.toLowerCase().includes('publish')
            );
            if (nextBtn) nextBtn.click();
        })()
    `);
    
    // Wait for publish
    await new Promise(r => setTimeout(r, 5000));
    
    // Final publish
    await client.js(`
        (() => {
            const buttons = document.querySelectorAll('button');
            const publishBtn = Array.from(buttons).find(b => 
                b.innerText?.toLowerCase().includes('publish') ||
                b.innerText?.toLowerCase().includes('save')
            );
            if (publishBtn) publishBtn.click();
        })()
    `);
    
    await new Promise(r => setTimeout(r, 3000));
    
    // Get URL
    let videoUrl = null;
    try {
        videoUrl = await client.js(`window.location.href`);
    } catch (e) {}
    
    return { success: true, url: videoUrl };
}

// ---------- Main ----------

async function main() {
    // Repair thumbnails mode - generate missing thumbnails for already-uploaded videos
    if (REPAIR_THUMBNAILS) {
        log('[REPAIR MODE] Generating missing thumbnails...');
        const outputDir = OUTPUT_DIR;
        
        if (!fs.existsSync(outputDir)) {
            log(`Output directory not found: ${outputDir}`);
            process.exit(1);
        }
        
        const videos = fs.readdirSync(outputDir)
            .filter(f => ['.mp4', '.webm', '.mov', '.avi'].includes(path.extname(f).toLowerCase()))
            .map(f => path.join(outputDir, f));
        
        log(`Found ${videos.length} videos in ${outputDir}`);
        
        let repaired = 0;
        for (const videoPath of videos) {
            const basename = path.basename(videoPath, path.extname(videoPath));
            const thumbPath = path.join(outputDir, `${basename}_thumb.jpg`);
            
            if (!fs.existsSync(thumbPath)) {
                log(`Generating thumbnail for: ${basename}`);
                const result = await extractThumbnail(videoPath, outputDir);
                if (result) {
                    repaired++;
                }
            }
        }
        
        log(`[DONE] Repaired ${repaired} thumbnails`);
        process.exit(0);
    }
    
    // Find videos
    const videos = findVideos(INPUT_DIR);
    log(`Found ${videos.length} videos in ${INPUT_DIR}`);
    
    if (videos.length === 0) {
        log('No videos found. Use --dir to specify a folder.');
        process.exit(0);
    }
    
    if (DRY_RUN) {
        log('[DRY RUN] Would upload:');
        videos.forEach((v, i) => {
            const info = parseVideoInfo(v);
            log(`  ${i + 1}. ${info.title}`);
        });
        if (CREATE_PLAYLIST) log(`  + Create playlist: "${CREATE_PLAYLIST}"`);
        process.exit(0);
    }
    
    // Launch browser
    const chrome = await launchBrowser();
    // cdpConnect returns the WebSocket URL, need to create and connect CDPClient
    const wsUrl = await cdpConnect(chrome);
    const client = new CDPClient(wsUrl);
    await client.connect();
    
    // Skip automated login - user will be logged in manually
    log('Make sure you are logged into YouTube Studio in Chrome');
    log('Navigate to: https://studio.youtube.com/upload');
    
    // Create playlist if requested (skip for now - manual creation works better)
    let playlistUrl = null;
    if (CREATE_PLAYLIST) {
        log('Skipping auto-playlist creation - please create manually in YouTube Studio');
        // playlistUrl = await createPlaylist(client, CREATE_PLAYLIST);
    }
    
    // Upload videos
    const results = [];
    for (let i = 0; i < videos.length; i++) {
        const videoPath = videos[i];
        const info = parseVideoInfo(videoPath);
        
        log(`\n[${i + 1}/${videos.length}] ${info.title}`);
        
        try {
            const result = await uploadVideo(client, info);
            results.push({ path: videoPath, ...result });
            log(`Success: ${result.url || 'uploaded'}`);
            
            // Move to uploaded
            const destDir = path.join(REPO, OUTPUT_DIR);
            if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });
            const destPath = path.join(destDir, path.basename(videoPath));
            try {
                fs.renameSync(videoPath, destPath);
            } catch (e) {
                warn(`Could not move file: ${e.message}`);
            }
        } catch (e) {
            warn(`Failed: ${e.message}`);
            results.push({ path: videoPath, success: false, error: e.message });
        }
        
        // Delay between uploads
        if (i < videos.length - 1) {
            log('Waiting 3s before next upload...');
            await new Promise(r => setTimeout(r, 3000));
        }
    }
    
    // Summary
    log('\n=== Summary ===');
    log(`Uploaded: ${results.filter(r => r.success).length}/${videos.length}`);
    if (playlistUrl) log(`Playlist: ${playlistUrl}`);
    
    const failed = results.filter(r => !r.success);
    if (failed.length > 0) {
        warn('Failed:');
        failed.forEach(f => warn(`  - ${path.basename(f.path)}: ${f.error}`));
    }
}

main().catch(e => {
    console.error(`Fatal: ${e.message}`);
    process.exit(1);
});
