// Twin OS service worker — sprint 2.
//
// Scope:
//   - Cache the shell on install so the app loads offline
//   - Cache-first for the shell HTML/CSS/JS (fast + offline-capable)
//   - Network-first for /data/songs/catalog.json (updates land fast;
//     falls back to the cached version when offline)
//   - Pass through everything else (Google Fonts, etc.)
//
// Why these strategies:
//   - The shell changes rarely; caching it forever is fine. A future
//     version-bump on CACHE invalidates and re-downloads.
//   - The catalog can be regenerated by `npm run index-songs` and
//     pushed at any time; we want the new version on next load, not
//     a stale one. Network-first with cache fallback is the right
//     trade-off.
//
// Background:
//   - Sprint 1 was a pass-through stub. This is the sprint 2 promotion.

const CACHE = 'twin-os-v2';
const SHELL = [
  './',
  './index.html',
  './manifest.webmanifest',
];
const CATALOG_PATHS = [
  '/data/songs/catalog.json',
  '../../data/songs/catalog.json',
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

function isShellRequest(url) {
  // Same-origin requests under the twin-os scope
  return url.pathname.endsWith('/index.html')
      || url.pathname.endsWith('/manifest.webmanifest')
      || url.pathname.endsWith('/sw.js')
      || url.pathname === self.registration.scope
      || url.pathname === self.registration.scope + '/';
}

function isCatalogRequest(url) {
  return CATALOG_PATHS.some(p => url.pathname.endsWith(p.replace(/^.*\//, '')))
      && url.pathname.includes('/data/songs/catalog.json');
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  let url;
  try { url = new URL(req.url); } catch (e) { return; }
  if (url.origin !== self.location.origin) return; // pass through cross-origin

  if (isShellRequest(url)) {
    // Cache-first for the shell.
    event.respondWith(
      caches.match(req).then(hit => hit || fetch(req).then(resp => {
        if (resp.ok) {
          const copy = resp.clone();
          caches.open(CACHE).then(c => c.put(req, copy));
        }
        return resp;
      }))
    );
    return;
  }

  if (isCatalogRequest(url)) {
    // Network-first for the catalog, fall back to cache.
    event.respondWith(
      fetch(req).then(resp => {
        if (resp.ok) {
          const copy = resp.clone();
          caches.open(CACHE).then(c => c.put(req, copy));
        }
        return resp;
      }).catch(() => caches.match(req).then(hit => hit || new Response(
        JSON.stringify({ items: [], roots: [], generatedAt: null, _offline: true }),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      )))
    );
    return;
  }

  // Pass through everything else (Google Fonts, etc.).
});